### ISSUE TITLE
New company suggestion: `Bexley London Borough Council`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#368] opened 2019-11-03 04:46 UTC
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "public body"
    ],
    "name": "Bexley London Borough Council",
    "address": "2 Watling Street\nBexleyheath \nDA6 7AT",
    "phone": "020 8303 7171",
    "email": "Nick.Hollier@bexley.gov.uk",
    "web": "https://www.bexley.gov.uk/",
    "slug": "bexleygovuk",
    "sources": [
        "https://github.com/datenanfragen/data/issues/368"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Bexley%20London%20Borough%20Council%22%2C%22address%22%3A%222%20Watling%20Street%5CnBexleyheath%20%5CnDA6%207AT%22%2C%22phone%22%3A%22020%208303%207171%22%2C%22email%22%3A%22Nick.Hollier%40bexley.gov.uk%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bexley.gov.uk%2F%22%2C%22slug%22%3A%22bexleygovuk%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F368%22%5D%7D)**

**Comment by m-rey** [comment] 2019-11-03 16:39
Duplicate of #367. Closing.

**Closed by m-rey** 2019-11-03 16:39 UTC
Labels: duplicate
