### ISSUE TITLE
Suggested update for company `direkta-marketing`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#463] opened 2019-12-11 20:01 UTC
The following suggestion was submitted through the website:

```
{
    "slug": "direkta-marketing",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads"
    ],
    "name": "Direkta Gesellschaft für Marketing mbH",
    "address": "Hoyendonk 12\n47638 Straelen\nDeuschland",
    "phone": "+49 2834 982614",
    "fax": "+49 2834 982617",
    "sources": [
        "https://github.com/datenanfragen/data/issues/185",
        "https://github.com/datenanfragen/data/issues/463"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22direkta-marketing%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Direkta%20Gesellschaft%20f%C3%BCr%20Marketing%20mbH%22%2C%22address%22%3A%22Hoyendonk%2012%5Cn47638%20Straelen%5CnDeuschland%22%2C%22phone%22%3A%22%2B49%202834%20982614%22%2C%22fax%22%3A%22%2B49%202834%20982617%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F185%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F463%22%5D%7D)**

**Comment by m-rey** [comment] 2019-12-12 13:25
Duplicate of https://github.com/datenanfragen/data/issues/464.
Closing.

**Closed by m-rey** 2019-12-12 13:25 UTC
Labels: duplicate
