### ISSUE TITLE
Suggested update for company `deutsche-post-direkt`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#184] opened 2019-07-10 12:47 UTC
The following suggestion was submitted through the website:

```
{
    "slug": "deutsche-post-direkt",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "addresses"
    ],
    "name": "Deutsche Post Direkt GmbH",
    "address": "Junkersring 57\n53844 Troisdorf\nDeutschland",
    "phone": "+49 800 9369373",
    "fax": "+49 2241 26611111",
    "email": "datenservice@postdirekt.de",
    "web": "https://service.postdirekt.de/pdportal/PublicServlet",
    "sources": [
        "https://service.postdirekt.de/pdportal/PublicServlet?command=content&page=datenschutz",
        "https://service.postdirekt.de/pdportal/PublicServlet?command=content&page=impressum",
        "https://github.com/datenanfragen/data/issues/184"
    ],
    "required-elements": [
        {
            "type": "input"
        }
    ],
    "comments": [
        null
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22deutsche-post-direkt%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22Deutsche%20Post%20Direkt%20GmbH%22%2C%22address%22%3A%22Junkersring%2057%5Cn53844%20Troisdorf%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20800%209369373%22%2C%22fax%22%3A%22%2B49%202241%2026611111%22%2C%22email%22%3A%22datenservice%40postdirekt.de%22%2C%22web%22%3A%22https%3A%2F%2Fservice.postdirekt.de%2Fpdportal%2FPublicServlet%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fservice.postdirekt.de%2Fpdportal%2FPublicServlet%3Fcommand%3Dcontent%26page%3Ddatenschutz%22%2C%22https%3A%2F%2Fservice.postdirekt.de%2Fpdportal%2FPublicServlet%3Fcommand%3Dcontent%26page%3Dimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F184%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%2C%22comments%22%3A%5Bnull%5D%7D)**

**Comment by baltpeter** [comment] 2019-07-10 18:05
Duplicate of #183.

**Closed by baltpeter** 2019-07-10 18:05 UTC
Labels: duplicate
